5/3/2018 12:37:09 AM: [ln:1356] Formulario: UploadMegaAPI() - Excepcion. Copiando archivo al server y guardando en BD. ERROR: One or more errors occurred..
5/3/2018 12:37:09 AM: [ln:1357] Formulario: UploadMegaAPI() - Excepcion. URL: .
5/20/2018 10:57:10 PM: [ln:676] Formulario: Guardar_Contexto() - Excepcion. Guardando en la base de datos. ERROR: An error occurred while updating the entries. See the inner exception for details..
5/20/2018 10:57:14 PM: [ln:676] Formulario: Guardar_Contexto() - Excepcion. Guardando en la base de datos. ERROR: An error occurred while updating the entries. See the inner exception for details..
5/20/2018 11:37:30 PM: [ln:676] Formulario: Guardar_Contexto() - Excepcion. Guardando en la base de datos. ERROR: An error occurred while updating the entries. See the inner exception for details..
5/20/2018 11:37:30 PM: [ln:676] Formulario: Guardar_Contexto() - Excepcion. Guardando en la base de datos. ERROR: An error occurred while updating the entries. See the inner exception for details..
5/20/2018 11:38:31 PM: [ln:676] Formulario: Guardar_Contexto() - Excepcion. Guardando en la base de datos. ERROR: An error occurred while updating the entries. See the inner exception for details..
5/20/2018 11:38:31 PM: [ln:676] Formulario: Guardar_Contexto() - Excepcion. Guardando en la base de datos. ERROR: An error occurred while updating the entries. See the inner exception for details..
5/20/2018 11:42:02 PM: [ln:676] Formulario: Guardar_Contexto() - Excepcion. Guardando en la base de datos. ERROR: An error occurred while updating the entries. See the inner exception for details..
5/20/2018 11:42:02 PM: [ln:676] Formulario: Guardar_Contexto() - Excepcion. Guardando en la base de datos. ERROR: An error occurred while updating the entries. See the inner exception for details..
7/27/2018 11:16:20 PM: [ln:79] Acceso: Perform_login() - Excepcion. Haciendo login. ERROR: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server).
